name: Build RingRTC Android Artifacts
run-name: Build RingRTC Android Artifacts (${{ github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "When true, don't upload to Sonatype"
        default: true
        required: false
        type: boolean
      runner:
        description: "Linux runner:"
        default: 'ubuntu-latest'
        required: true
env:
  CARGO_TERM_COLOR: always
  NDK_VERSION: '27.0.12077973'

jobs:
  build_android:
    name: Build Android

    runs-on: ${{ inputs.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Install NDK
      run: echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - run: rustup toolchain install $(cat rust-toolchain) --profile minimal --target aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - run: ./bin/fetch-artifact --platform android --release

    - run: ANDROID_NDK_HOME="$ANDROID_HOME/ndk/$NDK_VERSION" ./bin/build-aar --ringrtc-only --release

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-artifacts
        path: /home/runner/work/ringrtc/ringrtc/out/**/*.aar
